/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 classic.gltf 
Author: bobbyvanderaarde (https://sketchfab.com/bobbyvanderaarde)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-pistol-9c433a1a978943f4978a0a5b8131c606
Title: Stylized Pistol
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Classic(props) {
  const { nodes, materials } = useGLTF("/assets/classic.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, 0]} scale={0.01}>
        <mesh
          geometry={nodes.pistol_barrel_low__0.geometry}
          material={materials["Scene_-_Root"]}
          position={[186.345, -90.405, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.pistol_top_low__0.geometry}
          material={materials["Scene_-_Root"]}
          position={[186.345, -90.405, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.pistol_trigger_low__0.geometry}
          material={materials["Scene_-_Root"]}
          position={[186.345, -90.405, -0.052]}
          scale={47.669}
        />
        <mesh
          geometry={nodes.pistol_bot_low__0.geometry}
          material={materials["Scene_-_Root"]}
          position={[186.345, -90.405, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/classic.gltf");
