/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 knife.gltf 
Author: PureUgliness (https://sketchfab.com/PureUgliness)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/valorant-knife-c1a82eee57af4e11b820bec92b333f77
Title: Valorant Knife
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Knife(props) {
  const { nodes, materials } = useGLTF("/assets/knife.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 10, 0, Math.PI / 2]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.aiStandardSurface1SG}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.aiStandardSurface1SG}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/knife.gltf");
